apiVersion: apps/v1
kind: Deployment
metadata:
  name: omicsdi-ddi-webservice-deployment
  namespace: hari
spec:
  selector:
    matchLabels:
      app: omicsdi-ddi-webservice-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: omicsdi-ddi-webservice-pod
    spec:
      containers:
        - name: omicsdi-ddi-webservice
          imagePullPolicy: Always
          image: omicsdi/ddi-web-service:omicsdi.dev.01
          env:
            - name: DDI_MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_DB
            - name: DDI_MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_USER
            - name: DDI_MONGO_PASSWD
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_PASSWD
            - name: DDI_MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_PORT
            - name: DDI_MONGO_MACHINE_ONE
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: DDI_MONGO_MACHINE_TWO
            - name: DDI_MONGO_MACHINE_TWO
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: DDI_MONGO_MACHINE_ONE
            - name: DDI_MONGO_MACHINE_THREE
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: DDI_MONGO_MACHINE_THREE
            - name: DDI_MONGO_AUTH_DB
              valueFrom:
                secretKeyRef:
                  name: omicsdi
                  key: MONGO_AUTH_DB
            - name: DDI_PROFILE_ENDPOINT
              value: "http://dev.omicsdi.org/profilews"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: omicsdi-ddi-webservice
  namespace: hari
  labels:
    app: omicsdi-ddi-webservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: omicsdi-ddi-webservice-pod
